### ISSUE TITLE
Added value of Boutiques

### ISSUE THREAD

**Issue by matteomancini** [mtl-brainhack-school-2019/iron-meta-pipeline#4]
@gkiar I wanted to ask you what could be the added value of encapsulating a Nipype pipeline in Boutiques. If I understood correctly, the advantage is that you can then run it in the cloud and/or on a cluster. Can there be advantages also in terms of describing inputs and outputs of the whole pipeline?

**Comment by gkiar** [comment]
Hey @matteomancini !

Yes, you are correct in that one advantage is definitely making your code encapsulated and more easily runnable on things like clusters through existing platforms, such as CBRAIN, Clowdr, or others. This also attaches documentation to your tool so that users (i.e. you in 2 weeks) not only know what arguments are expected, but what those arguments mean, their possible values, etc...

It also keeps a record of your experiments and their outcomes, so you automatically have provenance for any experiment you run with your pipeline.

**Comment by matteomancini** [comment]
Hi Greg, thanks for the comment, in the end I did not use Boutiques and I am planning to automatically generated Docker containers for a given workflow.
